sudo: required
dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
    packages:
      - libclang-3.7-dev
env:
  global:
     - LD_LIBRARY_PATH=/usr/lib/llvm-3.7/lib
install:
  - "pip install --process-dependency-links ."
script:
  - "python setup.py test"